name: Rebuild and Deploy (Strapi webhook)

on:
  repository_dispatch:
    types: [ strapi_resource_published ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build & export
        env:
          STRAPI_URL: ${{ secrets.STRAPI_URL }}
          STRAPI_TOKEN: ${{ secrets.STRAPI_TOKEN }}
        run: |
          npm run build
          npm run export

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via rsync
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
        run: |
          echo "Deploying to ${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}"
          rsync -az --delete -e "ssh -p ${SSH_PORT} -o StrictHostKeyChecking=no" out/ ${SSH_USER}@${SSH_HOST}:${REMOTE_DIR}
